threads races test for runner unhiding race problem
Result is:
AssertionError: Expected 'mock' to have been called once. Called 2 times.
It happens since time_out_observer() may be called from:
1) wait_for() in one thread
2) feed() in another thread